name: DayJobs
description: A job class handler by Daybreak Studios
author: Daybreak Studios
softdepends: [Permissions]
depends: [Spout]
main: me.dbstudios.dayjobs.DayJobs
version: 2.0
commands:
    job:
        description: DayJobs command interface.
        usage: Command not recognized. Type /job help for assistance.