config:
    enabled: true
    debug: true
    default-name: Jobless
    all:
        can-use:
        - WOOD_SWORD
        - WOOD_HOE
        - STONE_SWORD
        - STONE_HOE
        - BOW
        can-place:
        - COBBLESTONE
        - DIRT
        - COBBLESTONE_STAIRS
        - WOOD_STAIRS
        - STEP
        - TORCH
        - WOOL
        - WOODEN_DOOR
        can-wear:
        - LEATHER_HELMET
        - LEATHER_CHESTPLATE
        - LEATHER_LEGGINGS
        - LEATHER_BOOTS
    jobs:
        Jobless:
            friendly-name: Jobless
            bio: I'll go look for a job tomorrow mom, I promise!
            can-use: []
            can-place: []
            can-wear: []
        Miner:
            friendly-name: Miner
            bio: A miner, skilled at extracting ore and minerals from the earth.
            can-use:
            - WOOD_PICKAXE
            - STONE_PICKAXE
            - IRON_PICKAXE
            - GOLD_PICKAXE
            - DIAMOND_PICKAXE
            - WOOD_SPADE
            - STONE_SPADE
            - IRON_SPADE
            - GOLD_SPADE
            - DIAMOND_SPADE
            can-place:
            - DIRT
            - COBBLESTONE
            can-wear:
            - IRON_HELMET
            - IRON_CHESTPLATE
            - IRON_LEGGINGS
            - IRON_BOOTS
        RSE:
            friendly-name: Redstone Engineer
            bio: Affectionately dubbed 'Stoners', Redstone Engineers are masters at created RS devices.
            can-use:
            - WOOD_PICKAXE
            - STONE_PICKAXE
            - WOOD_SPADE
            - STONE_SPADE
            can-place:
            - DIRT
            - COBBLESTONE
            - REDSTONE_WIRE
            - REDSTONE_TORCH_ON
            - STONE_BUTTON
            - DISPENSER
            - LEVER
            - STONE_PLATE
            - STONE_BUTTON
            - DIODE_BLOCK_OFF
            - WOOD_PLATE
            can-wear: []